// GENERATED CODE - DO NOT MODIFY BY HAND
// This is generated by auto_route package.
// Run: flutter pub run build_runner build
// to regenerate.

part of 'app_router.dart';

abstract class _$AppRouter extends RootStackRouter {
  _$AppRouter({super.navigatorKey});

  @override
  final Map<String, PageFactory> pagesMap = {
    SplashRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const SplashPage(),
      );
    },
    LoginRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const LoginPage(),
      );
    },
    MainRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const MainPage(),
      );
    },
    HomeRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const HomePage(),
      );
    },
    CampsiteListRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const CampsiteListPage(),
      );
    },
    CampsiteDetailRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const CampsiteDetailPage(),
      );
    },
    WalletRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const WalletPage(),
      );
    },
    CommunityRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const CommunityPage(),
      );
    },
    ProfileRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const ProfilePage(),
      );
    },
    ChargingRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const ChargingPage(),
      );
    },
  };
}

/// generated route for [SplashPage]
class SplashRoute extends PageRouteInfo<void> {
  const SplashRoute({List<PageRouteInfo>? children})
      : super(SplashRoute.name, initialChildren: children);

  static const String name = 'SplashRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const SplashPage();
    },
  );
}

/// generated route for [LoginPage]
class LoginRoute extends PageRouteInfo<void> {
  const LoginRoute({List<PageRouteInfo>? children})
      : super(LoginRoute.name, initialChildren: children);

  static const String name = 'LoginRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const LoginPage();
    },
  );
}

/// generated route for [MainPage]
class MainRoute extends PageRouteInfo<void> {
  const MainRoute({List<PageRouteInfo>? children})
      : super(MainRoute.name, initialChildren: children);

  static const String name = 'MainRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const MainPage();
    },
  );
}

/// generated route for [HomePage]
class HomeRoute extends PageRouteInfo<void> {
  const HomeRoute({List<PageRouteInfo>? children})
      : super(HomeRoute.name, initialChildren: children);

  static const String name = 'HomeRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const HomePage();
    },
  );
}

/// generated route for [CampsiteListPage]
class CampsiteListRoute extends PageRouteInfo<void> {
  const CampsiteListRoute({List<PageRouteInfo>? children})
      : super(CampsiteListRoute.name, initialChildren: children);

  static const String name = 'CampsiteListRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const CampsiteListPage();
    },
  );
}

/// generated route for [CampsiteDetailPage]
class CampsiteDetailRoute extends PageRouteInfo<CampsiteDetailRouteArgs> {
  CampsiteDetailRoute({
    Key? key,
    required String campsiteId,
    List<PageRouteInfo>? children,
  }) : super(
          CampsiteDetailRoute.name,
          args: CampsiteDetailRouteArgs(
            key: key,
            campsiteId: campsiteId,
          ),
          initialChildren: children,
        );

  static const String name = 'CampsiteDetailRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final args = data.argsAs<CampsiteDetailRouteArgs>();
      return CampsiteDetailPage(key: args.key, campsiteId: args.campsiteId);
    },
  );
}

class CampsiteDetailRouteArgs {
  const CampsiteDetailRouteArgs({
    this.key,
    required this.campsiteId,
  });

  final Key? key;

  final String campsiteId;

  @override
  String toString() {
    return 'CampsiteDetailRouteArgs{key: $key, campsiteId: $campsiteId}';
  }
}

/// generated route for [WalletPage]
class WalletRoute extends PageRouteInfo<void> {
  const WalletRoute({List<PageRouteInfo>? children})
      : super(WalletRoute.name, initialChildren: children);

  static const String name = 'WalletRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const WalletPage();
    },
  );
}

/// generated route for [CommunityPage]
class CommunityRoute extends PageRouteInfo<void> {
  const CommunityRoute({List<PageRouteInfo>? children})
      : super(CommunityRoute.name, initialChildren: children);

  static const String name = 'CommunityRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const CommunityPage();
    },
  );
}

/// generated route for [ProfilePage]
class ProfileRoute extends PageRouteInfo<void> {
  const ProfileRoute({List<PageRouteInfo>? children})
      : super(ProfileRoute.name, initialChildren: children);

  static const String name = 'ProfileRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      return const ProfilePage();
    },
  );
}

/// generated route for [ChargingPage]
class ChargingRoute extends PageRouteInfo<ChargingRouteArgs> {
  ChargingRoute({
    Key? key,
    required String chargerId,
    List<PageRouteInfo>? children,
  }) : super(
          ChargingRoute.name,
          args: ChargingRouteArgs(key: key, chargerId: chargerId),
          initialChildren: children,
        );

  static const String name = 'ChargingRoute';

  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final args = data.argsAs<ChargingRouteArgs>();
      return ChargingPage(key: args.key, chargerId: args.chargerId);
    },
  );
}

class ChargingRouteArgs {
  const ChargingRouteArgs({this.key, required this.chargerId});

  final Key? key;

  final String chargerId;

  @override
  String toString() {
    return 'ChargingRouteArgs{key: $key, chargerId: $chargerId}';
  }
}
